# Generated by Django 6.1.1 on 2026-09-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_dashboard', 'Can use the Store Dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
