# Generated by Django 4.2.29 on 2026-09-26 18:16

from django.db import migrations


def create_email_addresses(apps, schema_editor):
    """Create EmailAddress records for all users without one."""
    CustomUser = apps.get_model("accounts", "CustomUser")
    EmailAddress = apps.get_model("account", "EmailAddress")

    for user in CustomUser.objects.all():
        if not EmailAddress.objects.filter(user=user).exists():
            verified = user.is_superuser or user.is_staff
            EmailAddress.objects.create(
                user=user,
                email=user.email,
                verified=verified,
                primary=True,
            )


def reverse_email_addresses(apps, schema_editor):
    """Remove EmailAddress records created by this migration."""
    CustomUser = apps.get_model("accounts", "CustomUser")
    EmailAddress = apps.get_model("account", "EmailAddress")

    for user in CustomUser.objects.all():
        EmailAddress.objects.filter(user=user, email=user.email).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.RunPython(create_email_addresses, reverse_email_addresses),
    ]
