# Generated by Django 4.2.29 on 2026-09-26 18:26

from django.db import migrations, models
import uuid


def generate_order_numbers(apps, schema_editor):
    """Generate unique order numbers for all orders."""
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.all():
        order.order_number = uuid.uuid4()
        order.save()


def reverse_order_numbers(apps, schema_editor):
    """Reverse - clear the field."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                blank=True
            ),
        ),
        migrations.RunPython(generate_order_numbers, reverse_order_numbers),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                null=False
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'
            ),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'
            ),
        ),
    ]
