# Generated by Django 6.1.1 on 2026-09-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='vintage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
