# Generated by Django 6.1.1 on 2026-09-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_wine_vintage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
